package cmd

import (
	"strings"
	"testing"

	"github.com/drakeaharper/gerrit-cli/internal/gerrit"
)

func TestBuildMineQueryDefaults(t *testing.T) {
	got := buildMineQuery("self", "", "", "", "", "", "")
	if got != "commentby:self" {
		t.Errorf("expected bare commentby query, got %q", got)
	}
}

func TestBuildMineQueryAllFilters(t *testing.T) {
	got := buildMineQuery(
		"drake.harper@instructure.com",
		"ashafovaloff@instructure.com",
		"canvas-lms",
		"merged",
		"2026-01-01",
		"2026-07-01",
		`message:"flaky"`,
	)

	want := "commentby:drake.harper@instructure.com owner:ashafovaloff@instructure.com " +
		`project:canvas-lms status:merged after:2026-01-01 before:2026-07-01 message:"flaky"`
	if got != want {
		t.Errorf("query mismatch\n got: %q\nwant: %q", got, want)
	}
}

// An empty author must not emit a dangling "commentby:" term, which Gerrit
// rejects with a 400.
func TestBuildMineQueryOmitsEmptyTerms(t *testing.T) {
	got := buildMineQuery("", "", "", "", "", "", "  ")
	if got != "" {
		t.Errorf("expected empty query, got %q", got)
	}
}

// Account ID is authoritative: two accounts can share a display name, and a
// renamed account keeps its ID.
func TestAccountMatchesPrefersAccountID(t *testing.T) {
	want := &gerrit.Account{AccountID: 1000123, Email: "me@x.com", Name: "Me"}

	if !accountMatches(gerrit.Account{AccountID: 1000123, Name: "Different Name"}, want) {
		t.Error("same account ID should match regardless of name")
	}
	if accountMatches(gerrit.Account{AccountID: 999, Email: "me@x.com"}, want) {
		t.Error("different account ID should not match even with same email")
	}
}

func TestAccountMatchesFallsBackToEmailThenName(t *testing.T) {
	want := &gerrit.Account{Email: "me@x.com", Name: "Me"}

	if !accountMatches(gerrit.Account{Email: "ME@X.COM"}, want) {
		t.Error("email comparison should be case-insensitive")
	}
	if !accountMatches(gerrit.Account{Name: "me"}, want) {
		t.Error("should fall back to display name when no email or ID is present")
	}
	if accountMatches(gerrit.Account{Name: "Someone Else"}, want) {
		t.Error("different name should not match")
	}
}

func TestAccountMatchesNilTarget(t *testing.T) {
	if accountMatches(gerrit.Account{AccountID: 1}, nil) {
		t.Error("nil target should never match")
	}
}

// The lint bot posts comments with no author email; those must not be picked up
// as the target author just because both sides are empty.
func TestCommentByIgnoresAuthorlessComments(t *testing.T) {
	me := &gerrit.Account{AccountID: 1000123, Email: "me@x.com", Name: "Me"}
	bot := Comment{Message: "[ERROR] [biome] format", Author: ""}

	if commentBy(bot, me) {
		t.Error("authorless bot comment should not match the target author")
	}
}

// Posting inline comments always generates a "Patch Set N: (M comments)" change
// message. Those announce the inline comments rather than saying anything, so
// they must not survive into the corpus.
func TestMessageIsBoilerplate(t *testing.T) {
	cases := []struct {
		name string
		msg  gerrit.ChangeMessageInfo
		want bool
	}{
		{"comment receipt", gerrit.ChangeMessageInfo{Message: "Patch Set 1:\n\n(5 comments)"}, true},
		{"bare header", gerrit.ChangeMessageInfo{Message: "Patch Set 3:"}, true},
		{"vote only", gerrit.ChangeMessageInfo{Message: "Patch Set 2: Code-Review+2"}, true},
		{"single comment receipt", gerrit.ChangeMessageInfo{Message: "Patch Set 1:\n\n(1 comment)"}, true},
		{"autogenerated tag", gerrit.ChangeMessageInfo{Tag: "autogenerated:gerrit:merged", Message: "Change has been successfully merged"}, true},
		{"vote with rationale", gerrit.ChangeMessageInfo{Message: "Patch Set 2: Code-Review+2\n\nCorrect and minimal, the test is real."}, false},
		{"prose only", gerrit.ChangeMessageInfo{Message: "This needs a spec before it lands."}, false},
		{"receipt plus prose", gerrit.ChangeMessageInfo{Message: "Patch Set 1:\n\n(2 comments)\n\nSee the N+1 note."}, false},
	}

	for _, tc := range cases {
		if got := messageIsBoilerplate(tc.msg); got != tc.want {
			t.Errorf("%s: messageIsBoilerplate = %v, want %v", tc.name, got, tc.want)
		}
	}
}

func TestThreadHasAuthorFindsReplyDeepInChain(t *testing.T) {
	me := &gerrit.Account{AccountID: 1000123}
	thread := []Comment{
		{ID: "a", AuthorID: 555, Author: "Shaf", Message: "here is why"},
		{ID: "b", AuthorID: 1000123, Author: "Me", InReplyTo: "a", Message: "still an N+1"},
	}

	if !threadHasAuthor(thread, me) {
		t.Error("thread with my reply should match")
	}
	if threadHasAuthor(thread[:1], me) {
		t.Error("thread with only someone else's comment should not match")
	}
}

func TestRenderMineMarkdownIncludesReplyContext(t *testing.T) {
	r := &MinedResult{
		Author:       "Me",
		Query:        "commentby:self",
		ChangeCount:  1,
		CommentCount: 1,
		ThreadCount:  1,
		Changes: []MinedChange{{
			Number:  418380,
			Subject: "gradebook: tolerate undefined sticker key",
			Project: "canvas-lms",
			Status:  "MERGED",
			URL:     "https://gerrit.example.com/c/canvas-lms/+/418380",
			Threads: []MinedThread{{
				File:       "ui/shared/x.ts",
				Line:       42,
				Unresolved: true,
				Comments: []MinedComment{
					{Author: "Me", Mine: true, Message: "this guard hides the real bug"},
					{Author: "Shaf", Mine: false, Message: "fixed at the source in PS3"},
				},
			}},
		}},
	}

	out := renderMineMarkdown(r)

	for _, want := range []string{
		"# Comments by Me",
		"## [418380](https://gerrit.example.com/c/canvas-lms/+/418380)",
		"### `ui/shared/x.ts:42` (unresolved)",
		"**Me**",
		"**Shaf (reply)**",
		"> this guard hides the real bug",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("markdown missing %q\n---\n%s", want, out)
		}
	}
}
